#!/usr/bin/python3
import sys

class Car:
    def __init__(self, pos):
        self.pos = pos

    def move(pos):
        self.pos = pos

class RideRequest:
    def __init__(self, origin, destination, time):
        self.origin = origin
        self.destination = destination
        self.time = time

def main(args):
    string = ""
    F = open(args[1], "r")
    start_stuff = F.readline().split(' ')
    while string:
        string = F.readline()
        print (string)
    return 0


if __name__ == '__main__':
    exit(main(sys.argv))
